version: '3'

services:
   web:
     build: .
     container_name: web
     image: euknyaz/phalcon-docker-nginx
     ports:
       - "9000:80"
     restart: always
     volumes:
#       - ./html:/var/www/html
